src/Entity/Schedules.php
<?php

namespace App\Entity;

use App\Repository\SchedulesRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;

#[ORM\Entity(repositoryClass: SchedulesRepository::class)]
class Schedules
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\ManyToMany(targetEntity: Classes::class)]
    #[ORM\JoinTable(name: "schedules_classes")]
    private Collection $classes; // Change from ?Classes to Collection

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $start_time = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $end_time = null;

    #[ORM\Column(length: 100)]
    private ?string $room = null;

    public function __construct()
    {
        $this->classes = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    /**
     * @return Collection<int, Classes>
     */
    public function getClasses(): Collection
    {
        return $this->classes;
    }
    public function setClasses(Collection $class): static
    {
        $this->class = $class;

        return $this;
    }
    public function addClasses(Collection $class): self
    {
        if (!$this->classes->contains($class)) {
            $this->classes->add($class);
        }

        return $this;
    }


    public function removeClass(Classes $class): self
    {
        $this->classes->removeElement($class);

        return $this;
    }

    public function getStartTime(): ?\DateTimeInterface
    {
        return $this->start_time;
    }

    public function setStartTime(\DateTimeInterface $start_time): static
    {
        $this->start_time = $start_time;

        return $this;
    }

    public function getEndTime(): ?\DateTimeInterface
    {
        return $this->end_time;
    }

    public function setEndTime(\DateTimeInterface $end_time): static
    {
        $this->end_time = $end_time;

        return $this;
    }

    public function getRoom(): ?string
    {
        return $this->room;
    }

    public function setRoom(string $room): static
    {
        $this->room = $room;

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use App\Repository\UserRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;
use Symfony\Component\Security\Core\User\UserInterface;

#[ORM\Entity(repositoryClass: UserRepository::class)]
#[ORM\UniqueConstraint(name: 'UNIQ_IDENTIFIER_USERNAME', fields: ['username'])]
#[UniqueEntity(fields: ['username'], message: 'There is already an account with this username')]
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180)]
    private ?string $username = null;

    #[ORM\Column(type: 'json')]
    private array $roles = [];

    /**
     * @var string The hashed password
     */
    #[ORM\Column]
    private ?string $password = null;

    #[ORM\Column(length: 100)]
    private ?string $nom = null;

    #[ORM\Column(length: 100)]
    private ?string $prenom = null;

    #[ORM\Column(nullable: true)]
    private ?int $phone = null;

    #[ORM\Column(length: 100, nullable: true)]
    private ?string $adress = null;

    #[ORM\OneToOne(cascade: ['persist', 'remove'])]
    private ?Subscription $sub_id = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getUsername(): ?string
    {
        return $this->username;
    }

    public function setUsername(string $username): static
    {
        $this->username = $username;

        return $this;
    }

    /**
     * A visual identifier that represents this user.
     *
     * @see UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->username;
    }

    public function getRoles(): array
    {
        $roles = $this->roles;
        $roles[] = 'ROLE_USER';
    
        return array_unique($roles);
    }

    public function setRoles(array $roles): self
    {
        $this->roles = $roles;
    
        return $this;
    }

    /**
     * @see PasswordAuthenticatedUserInterface
     */
    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(string $password): static
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials(): void
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainPassword = null;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): static
    {
        $this->nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->prenom;
    }

    public function setPrenom(string $prenom): static
    {
        $this->prenom = $prenom;

        return $this;
    }

    public function getPhone(): ?int
    {
        return $this->phone;
    }

    public function setPhone(?int $phone): static
    {
        $this->phone = $phone;

        return $this;
    }

    public function getAdress(): ?string
    {
        return $this->adress;
    }

    public function setAdress(?string $adress): static
    {
        $this->adress = $adress;

        return $this;
    }

    public function getSubId(): ?Subscription
    {
        return $this->sub_id;
    }

    public function setSubId(?Subscription $sub_id): static
    {
        $this->sub_id = $sub_id;

        return $this;
    }
}

src/Form/UserType.php
<?php

namespace App\Form;

use App\Entity\Subscription;
use App\Entity\User;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\ChoiceType;

class UserType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('username')
            ->add('roles', ChoiceType::class, [
                'choices' => [
                    'Admin' => 'ROLE_ADMIN',
                    'User' => 'ROLE_USER',
                ],
                'expanded' => true, // Display as checkboxes
                'multiple' => true, // Allow multiple selections
            ])
            ->add('password')
            ->add('nom')
            ->add('prenom')
            ->add('phone')
            ->add('adress')
            ->add('sub_id', EntityType::class, [
                'class' => Subscription::class,
                'choice_label' => 'id',
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => User::class,
        ]);
    }
}

src/Controller/TimetableController.php
<?php

namespace App\Controller;

use App\Repository\SchedulesRepository;
use App\Repository\ClassesRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TimetableController extends AbstractController
{
    #[Route('/timetable', name: 'app_timetable')]
    public function index(SchedulesRepository $schedulesRepo, ClassesRepository $classesRepo): Response
    {
        // Fetch schedules, sorted by start_time directly from the database
        $schedules = $schedulesRepo->findBy([], ['start_time' => 'ASC']);  // Sort by start_time field (ascending)
        
        // Fetch all classes as usual
        $classes = $classesRepo->findAll();

        // Return the rendered template with sorted schedules
        return $this->render('timetable/index.html.twig', [
            'schedules' => $schedules,
            'classes' => $classes,
        ]);
    }
}

src/Controller/User/UserController.php
<?php

namespace App\Controller\User;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

class UserController extends AbstractController
{
    #[Route('/user/user', name: 'app_user_user')]
    public function index(): Response
    {
        return $this->render('user/user/index.html.twig', [
            'controller_name' => 'UserController',
        ]);
    }
}

src/Controller/admin/UserController.php
<?php

namespace App\Controller\admin;

use App\Entity\User;
use App\Form\UserType;
use App\Repository\UserRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Attribute\Route;

#[Route('/admin/user')]
final class UserController extends AbstractController
{
    #[Route(name: 'app_admin_user_index', methods: ['GET'])]
    public function index(UserRepository $userRepository): Response
    {
        return $this->render('admin/user/index.html.twig', [
            'users' => $userRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_admin_user_new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $user = new User();
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($user);
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/user/new.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_user_show', methods: ['GET'])]
    public function show(User $user): Response
    {
        return $this->render('admin/user/show.html.twig', [
            'user' => $user,
        ]);
    }

    #[Route('/{id}/edit', name: 'app_admin_user_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(UserType::class, $user);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('admin/user/edit.html.twig', [
            'user' => $user,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_admin_user_delete', methods: ['POST'])]
    public function delete(Request $request, User $user, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$user->getId(), $request->getPayload()->getString('_token'))) {
            $entityManager->remove($user);
            $entityManager->flush();
        }

        return $this->redirectToRoute('app_admin_user_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/user/timetable/index.html.twig
<!DOCTYPE html>

<title>Hello TimetableController!</title>

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code>C:/laragon/www/Gym/src/Controller/User/TimetableController.php</code></li>
        <li>Your template at <code>C:/laragon/www/Gym/templates/user/timetable/index.html.twig</code></li>
    </ul>
</div>


<section class="classtime-section class-time-table spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="section-title">
                    <h2>Classtime Table</h2>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="timetable-controls">
                    <ul>
                        <li class="active" data-tsfilter="all">all class</li>
                        <li >crossfit</li>
                        <li>lunge ball</li>
                        <li>ppsr</li>
                        <li>walls</li>
                        <li>candy</li>
                    </ul>
                </div>
            </div>
        </div>

        <div class="classtime-table">
            <table>
                <thead>
                    <tr>
                        <th></th>
                        <th>Monday</th>
                        <th>Tuesday</th>
                        <th>Wednesday</th>
                        <th>Thursday</th>
                        <th>Friday</th>
                        <th>Saturday</th>
                        <th>Sunday</th>
                    </tr>
                </thead>
                <tbody>
                    {% for schedule in schedules %}
                        <tr data-class="{{ schedule.room|lower }}">
                            <td class="workout-time">{{ schedule.startTime ? schedule.startTime|date('H:i') : '' }}</td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Monday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Tuesday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Wednesday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Thursday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Friday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Saturday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>

                            <td class="hover-bg ts-item">
                                {% if schedule.startTime|date('l') == 'Sunday' %}
                                    <span>{{ schedule.startTime|date('H:i') }} - {{ schedule.endTime|date('H:i') }}</span>
                                    <h6>{{ schedule.room }}</h6>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>
</section>
{% endblock %}